//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDrive
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadeBase", Namespace="http://gedoc2/INTEROP")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GDrive.Arquivo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GDrive.Ficha))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GDrive.Credenciais))]
    internal partial class EntidadeBase : object
    {
        
        private string UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arquivo", Namespace="http://gedoc2/INTEROP")]
    internal partial class Arquivo : GDrive.EntidadeBase
    {
        
        private byte[] ConteudoBase64BinaryField;
        
        private string DataDeCriacaoField;
        
        private string DescricaoField;
        
        private GDrive.Ficha FichaField;
        
        private string IDField;
        
        private string NomeField;
        
        private GDrive.StatusAprovacaoArquivo StatusField;
        
        private string TipoAnexoField;
        
        private string URLVisualizacaoTemporariaField;
        
        private string UsuarioDeCriacaoField;
        
        private int VersaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal byte[] ConteudoBase64Binary
        {
            get
            {
                return this.ConteudoBase64BinaryField;
            }
            set
            {
                this.ConteudoBase64BinaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string DataDeCriacao
        {
            get
            {
                return this.DataDeCriacaoField;
            }
            set
            {
                this.DataDeCriacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.Ficha Ficha
        {
            get
            {
                return this.FichaField;
            }
            set
            {
                this.FichaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.StatusAprovacaoArquivo Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string TipoAnexo
        {
            get
            {
                return this.TipoAnexoField;
            }
            set
            {
                this.TipoAnexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string URLVisualizacaoTemporaria
        {
            get
            {
                return this.URLVisualizacaoTemporariaField;
            }
            set
            {
                this.URLVisualizacaoTemporariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string UsuarioDeCriacao
        {
            get
            {
                return this.UsuarioDeCriacaoField;
            }
            set
            {
                this.UsuarioDeCriacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal int Versao
        {
            get
            {
                return this.VersaoField;
            }
            set
            {
                this.VersaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ficha", Namespace="http://gedoc2/INTEROP")]
    internal partial class Ficha : GDrive.EntidadeBase
    {
        
        private System.Collections.Generic.List<GDrive.Arquivo> ArquivosField;
        
        private string DataDeCriacaoField;
        
        private string IDField;
        
        private System.Collections.Generic.List<GDrive.Metadado> MetadadosField;
        
        private string NomeField;
        
        private string SistemaIntegradoField;
        
        private string URLAcessoViaWebClientField;
        
        private string URLAcessoViaWebClientDMZField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal System.Collections.Generic.List<GDrive.Arquivo> Arquivos
        {
            get
            {
                return this.ArquivosField;
            }
            set
            {
                this.ArquivosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string DataDeCriacao
        {
            get
            {
                return this.DataDeCriacaoField;
            }
            set
            {
                this.DataDeCriacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal System.Collections.Generic.List<GDrive.Metadado> Metadados
        {
            get
            {
                return this.MetadadosField;
            }
            set
            {
                this.MetadadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string SistemaIntegrado
        {
            get
            {
                return this.SistemaIntegradoField;
            }
            set
            {
                this.SistemaIntegradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string URLAcessoViaWebClient
        {
            get
            {
                return this.URLAcessoViaWebClientField;
            }
            set
            {
                this.URLAcessoViaWebClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string URLAcessoViaWebClientDMZ
        {
            get
            {
                return this.URLAcessoViaWebClientDMZField;
            }
            set
            {
                this.URLAcessoViaWebClientDMZField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credenciais", Namespace="http://gedoc2/INTEROP")]
    internal partial class Credenciais : GDrive.EntidadeBase
    {
        
        private string LoginField;
        
        private string SenhaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusAprovacaoArquivo", Namespace="http://gedoc2/INTEROP")]
    internal enum StatusAprovacaoArquivo : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Indefinido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anexado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejeitado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Em_Impasse = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Metadado", Namespace="http://gedoc2/INTEROP")]
    internal partial class Metadado : object
    {
        
        private string AtributoField;
        
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Atributo
        {
            get
            {
                return this.AtributoField;
            }
            set
            {
                this.AtributoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosArquivoCriacao", Namespace="http://gedoc2/INTEROP")]
    internal partial class DadosArquivoCriacao : object
    {
        
        private GDrive.ConfigAnexarArquivo ConfiguracoesOpcionaisField;
        
        private byte[] ConteudoBase64BinaryField;
        
        private string DescricaoOpcionalField;
        
        private string ExtensaoField;
        
        private GDrive.DadosFicha FichaField;
        
        private bool IncluirFTRField;
        
        private bool IncluirSubscribableField;
        
        private bool IncluirThumbnailField;
        
        private string NomeField;
        
        private string TipoAnexoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.ConfigAnexarArquivo ConfiguracoesOpcionais
        {
            get
            {
                return this.ConfiguracoesOpcionaisField;
            }
            set
            {
                this.ConfiguracoesOpcionaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal byte[] ConteudoBase64Binary
        {
            get
            {
                return this.ConteudoBase64BinaryField;
            }
            set
            {
                this.ConteudoBase64BinaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string DescricaoOpcional
        {
            get
            {
                return this.DescricaoOpcionalField;
            }
            set
            {
                this.DescricaoOpcionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Extensao
        {
            get
            {
                return this.ExtensaoField;
            }
            set
            {
                this.ExtensaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.DadosFicha Ficha
        {
            get
            {
                return this.FichaField;
            }
            set
            {
                this.FichaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool IncluirFTR
        {
            get
            {
                return this.IncluirFTRField;
            }
            set
            {
                this.IncluirFTRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool IncluirSubscribable
        {
            get
            {
                return this.IncluirSubscribableField;
            }
            set
            {
                this.IncluirSubscribableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool IncluirThumbnail
        {
            get
            {
                return this.IncluirThumbnailField;
            }
            set
            {
                this.IncluirThumbnailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string TipoAnexo
        {
            get
            {
                return this.TipoAnexoField;
            }
            set
            {
                this.TipoAnexoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigAnexarArquivo", Namespace="http://gedoc2/INTEROP")]
    internal partial class ConfigAnexarArquivo : GDrive.ConfigArquivo
    {
        
        private bool EmitirErroSeArquivoJaExisteField;
        
        private bool IgnorarExtensaoSeArquivoJaExisteField;
        
        private string NomeMaquinaCriacaoField;
        
        private string NomeUsuarioCriacaoField;
        
        private bool UploadSincronoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool EmitirErroSeArquivoJaExiste
        {
            get
            {
                return this.EmitirErroSeArquivoJaExisteField;
            }
            set
            {
                this.EmitirErroSeArquivoJaExisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool IgnorarExtensaoSeArquivoJaExiste
        {
            get
            {
                return this.IgnorarExtensaoSeArquivoJaExisteField;
            }
            set
            {
                this.IgnorarExtensaoSeArquivoJaExisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string NomeMaquinaCriacao
        {
            get
            {
                return this.NomeMaquinaCriacaoField;
            }
            set
            {
                this.NomeMaquinaCriacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string NomeUsuarioCriacao
        {
            get
            {
                return this.NomeUsuarioCriacaoField;
            }
            set
            {
                this.NomeUsuarioCriacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool UploadSincrono
        {
            get
            {
                return this.UploadSincronoField;
            }
            set
            {
                this.UploadSincronoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosFicha", Namespace="http://gedoc2/INTEROP")]
    internal partial class DadosFicha : object
    {
        
        private string IDField;
        
        private System.Collections.Generic.List<GDrive.Metadado> MetadadosField;
        
        private bool NaoVerificarSeExisteField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal System.Collections.Generic.List<GDrive.Metadado> Metadados
        {
            get
            {
                return this.MetadadosField;
            }
            set
            {
                this.MetadadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool NaoVerificarSeExiste
        {
            get
            {
                return this.NaoVerificarSeExisteField;
            }
            set
            {
                this.NaoVerificarSeExisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigArquivo", Namespace="http://gedoc2/INTEROP")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GDrive.ConfigRecuperarArquivo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GDrive.ConfigAnexarArquivo))]
    internal partial class ConfigArquivo : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigRecuperarArquivo", Namespace="http://gedoc2/INTEROP")]
    internal partial class ConfigRecuperarArquivo : GDrive.ConfigArquivo
    {
        
        private string AutorOperacaoField;
        
        private bool ConsiderarVersaoOcerizadaField;
        
        private bool IgnorarExtensaoField;
        
        private int VersaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string AutorOperacao
        {
            get
            {
                return this.AutorOperacaoField;
            }
            set
            {
                this.AutorOperacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool ConsiderarVersaoOcerizada
        {
            get
            {
                return this.ConsiderarVersaoOcerizadaField;
            }
            set
            {
                this.ConsiderarVersaoOcerizadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal bool IgnorarExtensao
        {
            get
            {
                return this.IgnorarExtensaoField;
            }
            set
            {
                this.IgnorarExtensaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal int Versao
        {
            get
            {
                return this.VersaoField;
            }
            set
            {
                this.VersaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigAuditoria", Namespace="http://gedoc2/INTEROP")]
    internal partial class ConfigAuditoria : object
    {
        
        private string ExecutorAcaoField;
        
        private string IPOrigemField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ExecutorAcao
        {
            get
            {
                return this.ExecutorAcaoField;
            }
            set
            {
                this.ExecutorAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string IPOrigem
        {
            get
            {
                return this.IPOrigemField;
            }
            set
            {
                this.IPOrigemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultInterop", Namespace="http://gedoc2/INTEROP")]
    internal partial class FaultInterop : object
    {
        
        private string CodigoField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosArquivoRecuperacao", Namespace="http://gedoc2/INTEROP")]
    internal partial class DadosArquivoRecuperacao : object
    {
        
        private GDrive.ConfigRecuperarArquivo ConfiguracoesOpcionaisField;
        
        private string ExtensaoField;
        
        private GDrive.DadosFicha FichaField;
        
        private string IDField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.ConfigRecuperarArquivo ConfiguracoesOpcionais
        {
            get
            {
                return this.ConfiguracoesOpcionaisField;
            }
            set
            {
                this.ConfiguracoesOpcionaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Extensao
        {
            get
            {
                return this.ExtensaoField;
            }
            set
            {
                this.ExtensaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.DadosFicha Ficha
        {
            get
            {
                return this.FichaField;
            }
            set
            {
                this.FichaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosArquivoAlteracao", Namespace="http://gedoc2/INTEROP")]
    internal partial class DadosArquivoAlteracao : object
    {
        
        private string AutorAlteracaoField;
        
        private string DescricaoField;
        
        private GDrive.StatusAprovacaoArquivo StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string AutorAlteracao
        {
            get
            {
                return this.AutorAlteracaoField;
            }
            set
            {
                this.AutorAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal GDrive.StatusAprovacaoArquivo Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gedoc2/INTEROP", ConfigurationName="GDrive.GEDService")]
    internal interface GEDService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/AnexarArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/AnexarArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/AnexarArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Arquivo> AnexarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoCriacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/VisualizarArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/VisualizarArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/VisualizarArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Arquivo> VisualizarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/BuscarConteudoArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/BuscarConteudoArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/BuscarConteudoArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Arquivo> BuscarConteudoArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ExcluirArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/ExcluirArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ExcluirArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Arquivo> ExcluirArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/AlterarArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/AlterarArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/AlterarArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Arquivo> AlterarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.DadosArquivoAlteracao novosDados, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ListarVersoesArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/ListarVersoesArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ListarVersoesArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarVersoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ListarVersoesDeArquivos", ReplyAction="http://gedoc2/INTEROP/GEDService/ListarVersoesDeArquivosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ListarVersoesDeArquivosFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarVersoesDeArquivosAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ListarTodasDescricoesArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/ListarTodasDescricoesArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ListarTodasDescricoesArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarTodasDescricoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ListarTodasAprovacoesArquivo", ReplyAction="http://gedoc2/INTEROP/GEDService/ListarTodasAprovacoesArquivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ListarTodasAprovacoesArquivoFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarTodasAprovacoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/CriarFicha", ReplyAction="http://gedoc2/INTEROP/GEDService/CriarFichaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/CriarFichaFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Ficha> CriarFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ExcluirFicha", ReplyAction="http://gedoc2/INTEROP/GEDService/ExcluirFichaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ExcluirFichaFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Ficha> ExcluirFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/ListarArquivosFicha", ReplyAction="http://gedoc2/INTEROP/GEDService/ListarArquivosFichaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/ListarArquivosFichaFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Ficha> ListarArquivosFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/AtualizarMetadadosFicha", ReplyAction="http://gedoc2/INTEROP/GEDService/AtualizarMetadadosFichaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/AtualizarMetadadosFichaFaultInteropFault", Name="FaultInterop")]
        System.Threading.Tasks.Task<GDrive.Ficha> AtualizarMetadadosFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/GEDService/PesquisarDocumentosPorMetadados", ReplyAction="http://gedoc2/INTEROP/GEDService/PesquisarDocumentosPorMetadadosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GDrive.FaultInterop), Action="http://gedoc2/INTEROP/GEDService/PesquisarDocumentosPorMetadadosFaultInteropFault" +
            "", Name="FaultInterop")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Ficha>> PesquisarDocumentosPorMetadadosAsync(GDrive.Credenciais credenciais, System.Collections.Generic.List<GDrive.Metadado> metadados, GDrive.ConfigAuditoria configsAuditoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal interface GEDServiceChannel : GDrive.GEDService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal partial class GEDServiceClient : System.ServiceModel.ClientBase<GDrive.GEDService>, GDrive.GEDService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GEDServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GEDServiceClient.GetBindingForEndpoint(endpointConfiguration), GEDServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GEDServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GEDServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GEDServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GEDServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GEDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<GDrive.Arquivo> AnexarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoCriacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.AnexarArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Arquivo> VisualizarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.VisualizarArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Arquivo> BuscarConteudoArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.BuscarConteudoArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Arquivo> ExcluirArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ExcluirArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Arquivo> AlterarArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.DadosArquivoAlteracao novosDados, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.AlterarArquivoAsync(credenciais, dadosArquivo, novosDados, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarVersoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ListarVersoesArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarVersoesDeArquivosAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ListarVersoesDeArquivosAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarTodasDescricoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ListarTodasDescricoesArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Arquivo>> ListarTodasAprovacoesArquivoAsync(GDrive.Credenciais credenciais, GDrive.DadosArquivoRecuperacao dadosArquivo, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ListarTodasAprovacoesArquivoAsync(credenciais, dadosArquivo, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Ficha> CriarFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.CriarFichaAsync(credenciais, dadosFicha, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Ficha> ExcluirFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ExcluirFichaAsync(credenciais, dadosFicha, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Ficha> ListarArquivosFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.ListarArquivosFichaAsync(credenciais, dadosFicha, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<GDrive.Ficha> AtualizarMetadadosFichaAsync(GDrive.Credenciais credenciais, GDrive.DadosFicha dadosFicha, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.AtualizarMetadadosFichaAsync(credenciais, dadosFicha, configsAuditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GDrive.Ficha>> PesquisarDocumentosPorMetadadosAsync(GDrive.Credenciais credenciais, System.Collections.Generic.List<GDrive.Metadado> metadados, GDrive.ConfigAuditoria configsAuditoria)
        {
            return base.Channel.PesquisarDocumentosPorMetadadosAsync(credenciais, metadados, configsAuditoria);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_GEDService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_GEDService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_GEDService))
            {
                return new System.ServiceModel.EndpointAddress("http://qwnap-bheged02.cemig.ad.corp/INTEROP/WebHost/Services/GEDService.svc/Soap11");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_GEDService))
            {
                return new System.ServiceModel.EndpointAddress("http://qwnap-bheged02.cemig.ad.corp/INTEROP/WebHost/Services/GEDService.svc/Soap12");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_GEDService,
            
            WSHttpBinding_GEDService,
        }
    }
}
